### ISSUE TITLE
Client side API ?

### ISSUE THREAD

**Issue by charly37** [geeky-T/react-node.bittrex.api#1]
Hi,

I m confuse. Is it a client/browser side API ? I have a nodeJS BE serving REACT FE pages and would like to do the call from the FE (without never going to the nodeJS BE). Is it possible with this API ?
```
I tried a quick test:
NodeBittrexApi.options({ 
      'apikey' : "toto", 
      'apisecret' : "toto", 
      'stream' : false, 
      'verbose' : false, 
      'cleartext' : false 
    });
    NodeBittrexApi.getmarkethistory( { market : 'BTC-LTC' }, function( data ) {
      console.log( data.result );
    });
```
but end up with a CORS issue :( so i even doubting a call from browser is possible.
![image](https://user-images.githubusercontent.com/6162615/34580103-b3bff31e-f159-11e7-898e-358b3a057748.png)

Thx for any clarification

**Comment by priyesh2609** [comment]
Sorry for the late reply. But yes, it is basically a react library :-D
